'use strict';

var products = [
  {
    id: 1,
    title: 'UA Tech &#8482;',
    description: 'Men\'s Short Sleeve Shirt',
    gender: 'Mens',
    category: 'Apparel',
    brand: 'Under Armour',
    variant: 'Black',
    price: 25.00,
    quantity: 1,
    tax: 0.06,
    shipping: 0.10,
    imageLocation: 'https://underarmour.scene7.com/is/image/Underarmour/V5-1326413-001_FC_Main?template=v65GridLarge&$wid=281&$hei=345',
  },
  {
    id: 2,
    title: 'UA Project Rock 2',
    description: 'Men\'s Training Shoes',
    gender: 'Mens',
    category: 'Shoes',
    brand: 'Under Armour',
    variant: 'Navy Blue',
    price: 140.00,
    quantity: 1,
    tax: 0.06,
    shipping: 0.10,
    imageLocation: 'https://underarmour.scene7.com/is/image/Underarmour/3022024-402_DEFAULT?template=v65GridLarge&$size=253,311&$wid=281&$hei=345',
  },
  {
    id: 3,
    title: 'UA Charged Cotton &reg; 2.0 Crew - 6-Pack',
    description: 'Adult Socks',
    gender: 'Mens',
    category: 'Apparel',
    brand: 'Under Armour',
    variant: 'Black',
    price: 20.00,
    quantity: 1,
    tax: 0.06,
    shipping: 0.10,
    imageLocation: 'https://underarmour.scene7.com/is/image/Underarmour/1298746-001_ASSTSTKDL?template=v65GridSmallRetina&$size=270,331&$wid=300&$hei=368',
  },
  {
    id: 4,
    title: 'HeatGear &reg; Armour Sport',
    description: 'Women\'s Leggings',
    gender: 'Womens',
    category: 'Apparel',
    brand: 'Under Armour',
    variant: 'Pink',
    price: 55.00,
    quantity: 1,
    tax: 0.06,
    shipping: 0.10,
    imageLocation: 'https://underarmour.scene7.com/is/image/Underarmour/V5-1355598-628_FC_Main?template=v65GridSmallRetina&$wid=300&$hei=368',
  },
  {
    id: 5,
    title: 'UA HOVR &#8482; Sonic 3',
    description: 'Women\'s Running Shoes',
    gender: 'Womens',
    category: 'Shoes',
    brand: 'Under Armour',
    variant: 'Turquoise',
    price: 110.00,
    quantity: 1,
    tax: 0.06,
    shipping: 0.10,
    imageLocation: 'https://underarmour.scene7.com/is/image/Underarmour/3022596-400_DEFAULT?template=v65GridSmallRetina&$size=270,331&$wid=300&$hei=368',
  },
  {
    id: 6,
    title: 'UA Fleece Taped Wordmark',
    description: 'Women\'s Hoodie',
    gender: 'Womens',
    category: 'Apparel',
    brand: 'Under Armour',
    variant: 'Hushed Pink',
    price: 60.00,
    quantity: 1,
    tax: 0.06,
    shipping: 0.10,
    imageLocation: 'https://underarmour.scene7.com/is/image/Underarmour/V5-1352744-662_FC_Main?template=v65GridSmallRetina&$wid=300&$hei=368',
  },
];